--- #YAML:1.0
name:                XML-LibXML-LazyBuilder
version:             0.06
abstract:            easy and lazy way to create XML document for XML::LibXML
license:             perl
author:              
    - Toru Hisai <toru@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    XML::LibXML:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
